### PR TITLE
Support systems with more than 9 reactors

### LINKED ISSUE #10: Update on DASGIP 6 planned?
Hi,

we got a software update to version 6 which is not working with detl unfortunately causing an error like this:

```
 ---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_10112\3709394288.py in <module>
----> 1 detl.parse('Y:\\ET\\Orga\\PTD\\BT\\07_Projekte\\2022 Technology Development\\02 Bearbeitung\\Jupyter Notebooks\\Project-Notebook\\SpoBE-Testumgebung\\JASA-8715\\JASA-8715.Control.csv')

~\Miniconda3\lib\site-packages\detl\__init__.py in parse(filepath, inoculation_times)
     59     """
     60     parser = get_parser(filepath)
---> 61     data = parser.parse(filepath)
     62 
     63     if inoculation_times:

~\Miniconda3\lib\site-packages\detl\parsing\dw5.py in parse(self, filepath)
    135 
    136         for _, reactor in dd.items():
--> 137             reactor._dataframe = common.transform_trackdata(
    138                 reactor.trackdata, columnmapping, core.DASwareVersion.V5
    139             )

~\Miniconda3\lib\site-packages\detl\parsing\common.py in transform_trackdata(trackdata, columnmapping, version)
    124     """
    125     transformed_data = pandas.DataFrame(
--> 126         index=trackdata.index,
    127         columns=["timestamp", "duration", "process_time"],
    128     )

AttributeError: 'NoneType' object has no attribute 'index'
```

Do you have plans to update DETL?

### PR DESCRIPTION
**Pull request by sleweke-bayer**
This PR adds support for systems with more than 9 reactors (e.g., DASBOX).
Also fixes #10.

### CODE REVIEW

**Comment by michaelosthege** [comment]
recheck

**Comment by sleweke-bayer** [comment]
- [X] The JuBiotech maintainers know my real name.

At least one of the following two applies:

- [X] The JuBiotech maintainers know my current employer.

- [ ] I am *not* making this contribution on behalf of my current employer.

**Comment by sleweke-bayer** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by sleweke-bayer** [comment]
recheck

**Review by michaelosthege — APPROVED** [review]
Thanks for the fixes, and your patience!

**Pull request merged**
